### ISSUE TITLE
findAll() should be able to take $where/$what arguments

### ISSUE THREAD

**Issue by NiklasAurora** [canax/database#2]
findAll("mail", $mail) could be used to return all entries by a specific user using its mail.

It would work much like how find() is working right now. However, it should not be necessary to send arguments (it should be null - findAll($column=null, $value=null))

**Comment by mosbth** [comment]
Fixed with `findAllWhere()` with commit https://github.com/canax/database/commit/287087cb867ad74bd6543eaab24707df2c093728.
