### ISSUE TITLE
update/save/delete should be able to take more than one id

### ISSUE THREAD

**Issue by NiklasAurora** [canax/database#4]
I have a table with an ID that consists of both its own ID and a foreign ID (let's say questionID and commentID which makes the unique id for a comment). I can not point to this comment with update/save/delete in its current state since they only take one id (which is not enough to define my comment).

A resonable solution would be a similar implementation to findAllWhere() which allows you to use both a single id and an array with id:s.

**Comment by mosbth** [comment]
Now implemented:
```
findAllWhere()
saveWhere()
updateWhere()
deleteWhere()
```
In v1.1.7.
